name=HRPWM
version=1.0.3
author=Arduino_dsPIC33CK
maintainer=Arduino_dsPIC33CK
sentence=High-Resolution PWM library for dsPIC33CK
paragraph=Hardware PWM generators PG1-PG8 with 250ps edge resolution, complementary outputs, dead-time, ADC trigger sync, and fault protection. Ideal for SMPS, motor control, and solar MPPT.
category=Signal Input/Output
url=
architectures=dspic33ck
