include("${CMAKE_CURRENT_LIST_DIR}/rule.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/file.cmake")

set(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_library_list )

# Handle files with suffix s, for group default-XC-DSC
if(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_FILE_TYPE_assemble)
add_library(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_assemble OBJECT ${dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_FILE_TYPE_assemble})
    dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_assemble_rule(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_assemble)
    list(APPEND dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_library_list "$<TARGET_OBJECTS:dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_assemble>")

endif()

# Handle files with suffix S, for group default-XC-DSC
if(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_FILE_TYPE_assemblePreproc)
add_library(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_assemblePreproc OBJECT ${dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_FILE_TYPE_assemblePreproc})
    dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_assemblePreproc_rule(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_assemblePreproc)
    list(APPEND dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_library_list "$<TARGET_OBJECTS:dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_assemblePreproc>")

endif()

# Handle files with suffix c, for group default-XC-DSC
if(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_FILE_TYPE_compile)
add_library(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_compile OBJECT ${dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_FILE_TYPE_compile})
    dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_compile_rule(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_compile)
    list(APPEND dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_library_list "$<TARGET_OBJECTS:dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_compile>")

endif()

# Handle files with suffix cpp, for group default-XC-DSC
if(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_FILE_TYPE_compile_cpp)
add_library(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_compile_cpp OBJECT ${dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_FILE_TYPE_compile_cpp})
    dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_compile_cpp_rule(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_compile_cpp)
    list(APPEND dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_library_list "$<TARGET_OBJECTS:dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_compile_cpp>")

endif()

# Handle files with suffix s, for group default-XC-DSC
if(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_FILE_TYPE_dependentObject)
add_library(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_dependentObject OBJECT ${dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_FILE_TYPE_dependentObject})
    dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_dependentObject_rule(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_dependentObject)
    list(APPEND dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_library_list "$<TARGET_OBJECTS:dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_dependentObject>")

endif()

# Handle files with suffix elf, for group default-XC-DSC
if(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_FILE_TYPE_bin2hex)
add_library(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_bin2hex OBJECT ${dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_FILE_TYPE_bin2hex})
    dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_bin2hex_rule(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_bin2hex)
    list(APPEND dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_library_list "$<TARGET_OBJECTS:dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_bin2hex>")

endif()

# Handle files with suffix elf, for group default-XC-DSC
if(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_FILE_TYPE_objcopy_lss)
add_library(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_objcopy_lss OBJECT ${dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_FILE_TYPE_objcopy_lss})
    dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_objcopy_lss_rule(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_objcopy_lss)
    list(APPEND dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_library_list "$<TARGET_OBJECTS:dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_objcopy_lss>")

endif()


# Main target for this project
add_executable(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_image_oykx6W2z ${dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_library_list})

if(NOT CMAKE_HOST_WIN32)
    set_target_properties(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_image_oykx6W2z PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_output_dir}")
endif()
set_target_properties(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_image_oykx6W2z PROPERTIES
    OUTPUT_NAME "default"
    SUFFIX ".elf")
target_link_libraries(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_image_oykx6W2z PRIVATE ${dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_default_XC_DSC_FILE_TYPE_link})
# Add the link options from the rule file.
dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_link_rule( dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_image_oykx6W2z)

# Call bin2hex function from the rule file
dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_bin2hex_rule(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_image_oykx6W2z)
if(CMAKE_HOST_WIN32)
    add_custom_command(
        TARGET dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_image_oykx6W2z
        POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E make_directory ${dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_output_dir}
        COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_FILE:dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_image_oykx6W2z> ${dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_output_dir}/${dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_original_image_name}
        BYPRODUCTS ${dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_output_dir}/${dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_original_image_name}
        COMMENT "Copying elf to out location")
    set_property(
        TARGET dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_image_oykx6W2z
        APPEND PROPERTY ADDITIONAL_CLEAN_FILES
        ${dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_output_dir}/${dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_original_image_name})
endif()

#Add objcopy steps
dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_objcopy_lss_rule(dsPIC33CK256MC005_Curiosity_Nano_Out_of_Box_Demo_default_image_oykx6W2z)

