/*
 * Arduino.h - Main Arduino API header for dsPIC33CK
 *
 * Provides the standard Arduino functions:
 *   - Digital I/O: pinMode, digitalWrite, digitalRead
 *   - Analog I/O: analogRead, analogWrite (PWM)
 *   - Timing: millis, micros, delay, delayMicroseconds
 *   - Math/Bit: min, max, abs, constrain, map, bit ops
 *   - Serial communication via HardwareSerial
 */

#ifndef ARDUINO_H
#define ARDUINO_H

#include <xc.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================
 * Constants
 * ============================================================ */

#define HIGH    1
#define LOW     0

#define INPUT           0
#define OUTPUT          1
#define INPUT_PULLUP    2

#define PI          3.1415926535897932384626433832795
#define HALF_PI     1.5707963267948966192313216916398
#define TWO_PI      6.283185307179586476925286766559
#define DEG_TO_RAD  0.017453292519943295769236907684886
#define RAD_TO_DEG  57.295779513082320876798154814105
#define EULER       2.718281828459045235360287471352

#define SERIAL      0x0
#define DISPLAY     0x1

#define LSBFIRST    0
#define MSBFIRST    1

#define CHANGE      1
#define FALLING     2
#define RISING      3

#define DEFAULT     0
#define EXTERNAL    1

#ifndef F_CPU
#define F_CPU       8000000UL
#endif

#ifndef FCY
#define FCY         (F_CPU / 2)
#endif

/* ============================================================
 * Macros
 * ============================================================ */

#define min(a,b)        ((a)<(b)?(a):(b))
#define max(a,b)        ((a)>(b)?(a):(b))
#define abs(x)          ((x)>0?(x):-(x))
#define constrain(amt,low,high) ((amt)<(low)?(low):((amt)>(high)?(high):(amt)))
#define round(x)        ((x)>=0?(long)((x)+0.5):(long)((x)-0.5))
#define radians(deg)    ((deg)*DEG_TO_RAD)
#define degrees(rad)    ((rad)*RAD_TO_DEG)
#define sq(x)           ((x)*(x))

#define lowByte(w)      ((uint8_t)((w) & 0xff))
#define highByte(w)     ((uint8_t)((w) >> 8))

#define bitRead(value, bit)         (((value) >> (bit)) & 0x01)
#define bitSet(value, bit)          ((value) |= (1UL << (bit)))
#define bitClear(value, bit)        ((value) &= ~(1UL << (bit)))
#define bitToggle(value, bit)       ((value) ^= (1UL << (bit)))
#define bitWrite(value, bit, bitvalue) ((bitvalue) ? bitSet(value, bit) : bitClear(value, bit))
#define bit(b)                      (1UL << (b))

typedef unsigned int word;
typedef uint8_t byte;
typedef bool boolean;

/* ============================================================
 * Digital I/O
 * ============================================================ */

void pinMode(uint8_t pin, uint8_t mode);
void digitalWrite(uint8_t pin, uint8_t val);
int  digitalRead(uint8_t pin);

/* Peripheral Pin Select number for a pin (RBn -> 32+n, RCn -> 48+n, RDn -> 64+n),
 * or -1 for a pin that has none -- which is every PORTA pin, and PORTE on the
 * MP508. Not an Arduino standard function; it is here because remapping a
 * peripheral onto a pin by hand needs the RP number, and the rule was previously
 * written out only in the per-variant PWMn_RP constants. */
int16_t pinToRP(uint8_t pin);

/* ============================================================
 * Analog I/O
 * ============================================================ */

int  analogRead(uint8_t pin);
void analogWrite(uint8_t pin, int val);
void analogReference(uint8_t mode);

/* ============================================================
 * Timing
 * ============================================================ */

unsigned long millis(void);
unsigned long micros(void);
void delay(unsigned long ms);
void delayMicroseconds(unsigned int us);

/* ============================================================
 * Advanced I/O
 * ============================================================ */

/*
 * tone() borrows SCCP4, which is also analogWrite()'s D8 channel, so a tone and
 * analogWrite(8, ...) are mutually exclusive -- whichever was called last wins,
 * silently. Same caveat stock AVR Arduino carries for pins 3 and 11. Any pin
 * works, including PORTA pins with no PPS number, because the square wave is
 * generated by toggling LATx from an ISR rather than by routing a PWM output.
 *
 * The default duration is declared only for C++, because C has no default
 * arguments -- and it has to be a default rather than an overload, since a
 * C-linkage function cannot be overloaded. It is what makes the common
 * two-argument tone(pin, freq) call work. The definition in wiring_tone.c must
 * not repeat the default.
 */
#ifdef __cplusplus
void tone(uint8_t pin, unsigned int frequency, unsigned long duration = 0);
#else
void tone(uint8_t pin, unsigned int frequency, unsigned long duration);
#endif
void noTone(uint8_t pin);
unsigned long pulseIn(uint8_t pin, uint8_t state, unsigned long timeout);
void shiftOut(uint8_t dataPin, uint8_t clockPin, uint8_t bitOrder, uint8_t val);
uint8_t shiftIn(uint8_t dataPin, uint8_t clockPin, uint8_t bitOrder);

/* ============================================================
 * External Interrupts
 * ============================================================ */

/*
 * The first argument is a PIN NUMBER, not an interrupt number --
 * attachInterrupt(0, ...) means D0, as on every non-AVR core.
 * digitalPinToInterrupt(p) is the identity for a valid pin (see pins_arduino.h)
 * and exists only so that stock sketches written for AVR compile unchanged.
 *
 * Backed by Change Notification, so every pin on every port works, there is no
 * limit on how many can be attached at once, and CHANGE is native rather than
 * emulated. mode is CHANGE, FALLING or RISING. Nothing here can fail for lack of
 * hardware; an invalid pin, mode or handler is a silent no-op, matching upstream.
 *
 * attachInterrupt() sets the pin to INPUT (a hardware requirement -- CN only
 * reports pins whose TRISx bit is set) and clears its analog mux, but leaves the
 * internal pull-up alone, so this works and keeps the pull-up:
 *     pinMode(p, INPUT_PULLUP);
 *     attachInterrupt(digitalPinToInterrupt(p), fn, FALLING);
 *
 * INSIDE A HANDLER. Handlers run at IPL2, below millis() (IPL4) and Serial RX
 * (IPL3), which is what makes them usable:
 *   - millis() and micros() return live values.
 *   - delay() works rather than deadlocking -- but it is still a spin loop
 *     holding off everything at or below IPL2, so don't.
 *   - digitalRead()/digitalWrite()/analogRead() are safe.
 *   - Serial.print() works, but is NOT reentrant: preempting a print in the
 *     mainline interleaves the two outputs mid-string. Nothing hangs or corrupts;
 *     it just looks like garbage. Set a flag and print from loop() instead.
 *   - Variables shared with the mainline need "volatile", and anything wider than
 *     16 bits (a long, a float, millis()) needs a noInterrupts()/interrupts()
 *     pair around the mainline read or it can be torn.
 */
void attachInterrupt(uint8_t pin, void (*userFunc)(void), int mode);
void detachInterrupt(uint8_t pin);
void interrupts(void);
void noInterrupts(void);

/* ============================================================
 * Map function
 * ============================================================ */

long map(long value, long fromLow, long fromHigh, long toLow, long toHigh);

/* ============================================================
 * System
 * ============================================================ */

void init(void);
void setup(void);
void loop(void);

#ifdef __cplusplus
}
#endif

/* Include variant pin definitions */
#include "pins_arduino.h"

/* Include Serial object (must be after pins_arduino.h for PPS macros) */
#include "HardwareSerial.h"

#endif /* ARDUINO_H */
